### ISSUE TITLE
Cannot find the paper link

### ISSUE THREAD

**Issue by ForrestPi** [MCG-NJU/SADRNet#1]
Could you please update the paper link?

**Comment by wanglimin** [comment]
Thanks for your attention. The manuscript is still under review. 

The title is: SADRNet: Self-Aligned Dual Face Regression Networks for Robust 3D Dense Face Alignment and Reconstruction.

We will update the repo after the paper is accepted.

**Comment by wanglimin** [comment]
Now the paper is available: https://arxiv.org/abs/2106.03021
