### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ofirkris** [MCG-NJU/SADRNet#11]
Hey guys

Thanks for sharing your work and releasing the code. However officially you would need to add a license to allow people to use your code or to build upon it for academic/industrial research.

You can probably add Apache-2.0 License like the mmediting (https://github.com/open-mmlab/mmediting) or BSD License like pix2pixHD (https://github.com/NVIDIA/pix2pixHD) or anything else

Do you plan to add a License to your code?

**Comment by wanglimin** [comment]
Hi, Thanks for your suggestion. We have added the licence.
