### ISSUE TITLE
0 data added

### ISSUE THREAD

**Issue by laceyliao** [MCG-NJU/SADRNet#14]
![image](https://user-images.githubusercontent.com/18067731/141961926-5cd88f8b-9117-46e9-ae0a-8c9b0a67024a.png)
I think is something wrong with the code, it can't read the image in the folder. After I change the code, there is no corresponding _info.mat :
![image](https://user-images.githubusercontent.com/18067731/141962450-a2f8fc3e-bde3-4287-b613-a9aa7e3319af.png)
What the format of testing images should be? 
Thank you for your response.

**Comment by NocturnalPig** [comment]
@laceyliao Hello, I have the same problem as you. Have you solved it？

**Comment by laceyliao** [comment]
@NocturnalPig 
You should use the 300W or AFLW dataset, in which each image has ".mat" file, or you can generate a ".mat" file for your own dataset.

**Comment by jacquelinelala** [comment]
> 

Hey, great work! Could you offer a test code that can infer any picture? @reshow

**Comment by gd1925** [comment]
Hi everyone, has anyone managed to run it on any given image? I am trying to run it on some random face image, but it shows error related to the line - 
![image](https://github.com/MCG-NJU/SADRNet/assets/50822928/2020823f-eb6a-4234-b98b-24f5d9678dc8)

One of the answers here suggests to use a Pytorch version 1.2.0. I am using the same version, but the error persists. 
https://github.com/MCG-NJU/SADRNet/issues/9
