### ISSUE TITLE
How to extract Point Cloud?

### ISSUE THREAD

**Issue by noumanriazkhan** [MCG-NJU/SADRNet#15]
Thanks for sharing this project. As mentioned in the paper

> we choose the face region containing 19K points

I am interested in extracting point cloud and use CPD to skin displacement. Can you point me to location to extract these point clouds?

Thanks

**Comment by reshow** [comment]
We follow PRNet as they mentioned in [https://arxiv.org/pdf/1803.07835.pdf](https://arxiv.org/pdf/1803.07835.pdf).
>  Although our method output more complete
face point clouds than VRN, we only choose the common face region to compare
the performance, 19K points are used for the evaluation.

We crop out the center area of the face in the UVmap to make the output face model similar to VRN for evaluation.
