### ISSUE TITLE
Issue for running the pre-trained model with Pytorch version > 1.4

### ISSUE THREAD

**Issue by amin-jourabloo** [MCG-NJU/SADRNet#17]
Hi, 
Thanks a lot for sharing the code and the pre-trained model of your awesome paper. Really appreciated.

We tried to load and test the pre-trained model, but we face this error: Unexpected tensor shape for one of the building blocks, class ResBlock4(nn.Module).. 

It seems that there was an update for the Conv layers after version 1.4 (https://discuss.pytorch.org/t/did-conv2d-shapes-change-between-torch-1-4-0-and-1-6-0/93859).

I like to ask whether you can share with us a new pre-trained model that trained with Pytorch version > 1.4 ?

Thanks,
Amin

**Comment by reshow** [comment]
I'm sorry that we have not solved this problem either.
