### ISSUE TITLE
Can you provide the data import and test code on the Florence dataset?

### ISSUE THREAD

**Issue by HeBangYan** [MCG-NJU/SADRNet#19]
I did not find **the data import and test code on the FLorence dataset** , could you please provide a copy?
Thank you very much for sharing. :)

**Comment by reshow** [comment]
I'm sorry the codes related to Florence are not organized into this repo. A very early version of data generating method is in https://github.com/reshow/SDRN/blob/master/renderMICC.py.

**Comment by HeBangYan** [comment]
> I'm sorry the codes related to Florence are not organized into this repo. A very early version of data generating method is in https://github.com/reshow/SDRN/blob/master/renderMICC.py.

Many thanks. 😁
