### ISSUE TITLE
where is the uv_triangles.npy

### ISSUE THREAD

**Issue by arukumattsun** [MCG-NJU/SADRNet#2]
Hello, thanks for your excellent work!

I tried run predict, but I can't run it because "uv_triangles.npy" is not found. 
How do you generate this file?

**Comment by arukumattsun** [comment]
I have found the get_uv_triangles function and will close this issue.

**Comment by xkyang00** [comment]
You can just fix L16 in config.py to slove this problem.

Before:
`UV_TRIANGLES_PATH = '../data/uv_data/uv_triangles.npy'`

After:
`UV_TRIANGLES_PATH = 'data/uv_data/uv_triangles.npy'`
