### ISSUE TITLE
how to generate uv_posmap_path for example images?

### ISSUE THREAD

**Issue by chankcalfred** [MCG-NJU/SADRNet#23]
Hello, 

Can someone get the predict task done with test images rather than a dataset? I tried to use some test images to test the program, however, it requests uv_posmap_path for each test image (in dataloader.py). I am not sure how these uv_posmap files are generated. Please help.

Thank in advance for your help.

**Comment by gd1925** [comment]
Hi @thlnoftus,
were you able to test the code for other images? I tried to run the code - predict.py for different images but I always get the wrong mask and keypoints. 
![image](https://github.com/MCG-NJU/SADRNet/assets/50822928/be226ef0-d576-4993-8dd1-3fc17a2d4699)
and the final keypoints look something like this - 
![image](https://github.com/MCG-NJU/SADRNet/assets/50822928/cdddaf5c-147a-4d5b-8bc8-34f744537ec9)
Any pointers that you can give me?

**Comment by chankcalfred** [comment]
@gd1925 Hi, based on your results, I guess you need to conduct face detection and facial landmark detection first, e.g. mtcnn. Looking forward to hear the update from you.

**Comment by gd1925** [comment]
Hi @thlnoftus, Ohh okay I will try it out. Thank you for you reply!
So does it mean the mtcnn should be used on the image in a separate code? and then I should pass the face cropped images of size 256 x 256 in predict.py is it?

**Comment by chankcalfred** [comment]
@gd1925 I am not sure as I have forgot what I have done. mtcnn should not included in this repo, you may search for another repo to conduct mtcnn as preporcessing. I am not sure the exact crop size of the input, you may try 256*256.
