### ISSUE TITLE
 No such file or directory: 'data/dataset/300W_LP_crop/all_image_data.pkl'

### ISSUE THREAD

**Issue by deepdarkfans** [MCG-NJU/SADRNet#3]
When I finish running prepare_dataset.py, there is no` all_image_data.pkl` file in `300W_LP_crop`, but there is one in `AFLW2000_crop`, and then when I run` train_block_data.py`, it returns an error: `train_blocks/ 131.pkl `file cannot be found. Am I missing some steps?

**Comment by eternalland** [comment]
hello, can you tell me how do you solve this problem? thank you.
