### ISSUE TITLE
About data augmentation for occlusion

### ISSUE THREAD

**Issue by MariaWang96** [MCG-NJU/SADRNet#5]
Thanks for your great work!!!

During the process of data augmentation, especially for the occlusion augmentation, I find that the whole face region in the image would be occluded for its random character. I want to know your operation on these ill images. Maybe just delete these images? Or others?

Hope for your reply! Thanks again!

**Comment by reshow** [comment]
We do not delete such images. We hope that even if the whole face region is occluded, the network can still infer the approximate face orientation from the secondary information such as the person's hair and neck.

**Comment by MariaWang96** [comment]
Thanks for your reply! I also retain these images in my project for training and validation. 
 : )
